client-side/src/App.js

did the uhm, the, the push, added files and all that on components, and structured app.js

made edits on setup

---

client-side/src/App.css

did the um the thing, the basic layout css with the um spicy, um chicken, for thew web app

added basic elements of the web app to the css

---

client-side/src/App.js
client-side/src/components/signup.js

added a sign up form in components

---

client-side/src/App.js
client-side/src/components/signup.js

litewawy added comment and fixed export

litewally added a comment and fixed export

---

client-side/src/components/login.js
client-side/src/components/navbar.js

aslalalalalamalallamas made a login screen.. GRAPE

made login screen

---

client-side/src/App.js
client-side/src/components/home.js
client-side/src/components/navbar.js

what do you mean by that ? >:(

added a temp modal in home page

---

server/config/connection.js
server/package-lock.json
server/package.json

added dependencies needed for image upload

added packages for image uploads

---

client-side/package-lock.json
client-side/package.json
client-side/src/App.css
client-side/src/App.js
client-side/src/components/slideup.js
client-side/src/index.js

i added the bottom sheet am pilot GRAPE

added bottom sheet, still need to fix up and update

---

client-side/src/App.js
client-side/src/components/slideup.js
client-side/src/index.js

Party Rock??? we got it imported bruv

got it to work only need to style slideup to look good

---

client-side/src/components/slideup.js

added search bar to bottom sheet

---

client-side/src/App.css
client-side/src/components/slideup.js

okay so i did have to push this is the more functional bottom sheet we still need to fix some components though

sending this push just in case

---

client-side/src/App.css
client-side/src/App.js
client-side/src/components/slideup.js

made some edits to enhance front end view YA GRAAAAAPE

made some edits accept it

---

server/schemas/resolvers.js

added image upload logic to resolvers.js

---

server/seeders/seed.js
server/seeders/userSeeds.json

Added user seeds and logic to seeds.js

added user seeds

---

client-side/src/App.css
client-side/src/components/slideup.js

GRAAAAAAAAAAAAAAAAAAAAAPE IS FIXED bottom sheet is fixed!!!!

FINALLY FIXED LES GO

---

client-side/src/components/slideup.js

created an auth js to start linking things together

---

client-side/src/App.js

readjusted App function in App.js

---

client-side/src/utils/auth.js

populated auth.js client side, peelot GRAPE

populated auth.js client side

---

client-side/src/App.js

added extra import statement to App.js

---

client-side/package-lock.json
client-side/package.json
client-side/src/App.js

added apollo client to app.js and npm router dom

added new npm

---

client-side/src/App.js
client-side/src/components/home.js
client-side/src/components/modal.js

made modal.js

---

client-side/src/components/home.js

home is home and home is home and home is home is home

created home page where it has main page

---

client-side/src/App.js
client-side/src/components/home.js
client-side/src/utils/auth.js

vsdagbraebhrtedrthrfrb ndtgshbrfbrdsz WE DID IT YAY

was able to make home connect to route

---

client-side/package-lock.json
client-side/package.json
client-side/src/App.css
client-side/src/components/cam.js
client-side/src/components/loading.js

loading screen, done, cam started

created loading screen and cam

---

client-side/src/utils/queries.js
package.json
server/schemas/typeDefs.js

Added queries to get all users and get all fountains to the client-side queries.js

added user and fountain queries to client-side

---

client-side/src/App.css
client-side/src/App.js
client-side/src/components/cam.js
client-side/src/components/loading.js

made loading screen work GRAAAAAAPE

created the loading screen where it also gives an options

---

client-side/src/components/cam.js

Added the use of the users webcam and ability to capture an image with it.

added camera functionality to cam.js

---

client-side/src/components/login.js
client-side/src/components/signup.js
client-side/src/utils/auth.js

replaced placeholder logo for signup and login forms

---

client-side/src/components/loading.js
client-side/src/components/signup.js
client-side/src/utils/auth.js

added link to tags from loading.js

---

client-side/src/App.js

fixed signup portion

---

client-side/src/App.js

made guest route to home

---

client-side/src/components/login.js

La música de Harry Fraud
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, yeah
Yeah, what, what
You cannot hop in my car
Bentley coupe riding with stars
Yeah, what, what!
I keep a Glock like a cop
Ayy, yeah (yeah)
She give the top in the drop
Yeah, ayy

added login.js

---

client-side/src/components/Map.js
client-side/src/components/slideup.js

fixed bottomsheet

---

client-side/src/App.css
client-side/src/App.js
client-side/src/components/loading.js

fixed the link to buttons and how they link

---

client-side/src/components/Map.js
server/seeders/demoFountain.json

fixed the bottom sheet and search

---

client-side/src/App.css
client-side/src/components/cam.js

fixed up camera portion

---

client-side/src/App.css

fixed up options box for the loading screen

---

client-side/src/components/navbar.js

made conditional route for camera

made another route
